# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hottie < Formula
  desc ""
  homepage "https://github.com/aosasona/homebrew-hottie"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aosasona/hottie/releases/download/v1.0.2/hottie_Darwin_arm64.tar.gz"
      sha256 "c5007aecec4cca47df85f933cfdff29c9913fd403c78bf88248a827ab209c3dd"

      def install
        bin.install "hottie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/hottie/releases/download/v1.0.2/hottie_Darwin_x86_64.tar.gz"
      sha256 "1cadb6718091daa9cb79f161dfa0e937786b02bf400f2ab91334a8ca9dffe689"

      def install
        bin.install "hottie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aosasona/hottie/releases/download/v1.0.2/hottie_Linux_arm64.tar.gz"
      sha256 "93c245f5cdae1257417361087c90f7410a386fd5ba671b44e68653c51aae91c6"

      def install
        bin.install "hottie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/hottie/releases/download/v1.0.2/hottie_Linux_x86_64.tar.gz"
      sha256 "ef63ff7d5b75abcf01f9856e6194f340599fd84aba128668748720ec2902311a"

      def install
        bin.install "hottie"
      end
    end
  end
end
